In [4]:
import numpy as np
import random
import pandas as pd
eruptions = pd.read_csv('C://Users//47129//Desktop//geyser_csv//eruptions.csv',header=None)
waiting = pd.read_csv('C://Users//47129//Desktop//geyser_csv//waiting.csv',header=None)

In [7]:
print(eruptions.shape)
print(waiting.shape)

(272, 1)
(272, 1)

In [41]:
eruptions
#waiting

         0
0    3.600
1    1.800
2    3.333
3    2.283
4    4.533
5    2.883
6    4.700
7    3.600
8    1.950
9    4.350
10   1.833
11   3.917
12   4.200
13   1.750
14   4.700
15   2.167
16   1.750
17   4.800
18   1.600
19   4.250
20   1.800
21   1.750
22   3.450
23   3.067
24   4.533
25   3.600
26   1.967
27   4.083
28   3.850
29   4.433
..     ...
242  4.933
243  2.900
244  4.583
245  3.833
246  2.083
247  4.367
248  2.133
249  4.350
250  2.200
251  4.450
252  3.567
253  4.500
254  4.150
255  3.817
256  3.917
257  4.450
258  2.000
259  4.283
260  4.767
261  4.533
262  1.850
263  4.250
264  1.983
265  2.250
266  4.750
267  4.117
268  2.150
269  4.417
270  1.817
271  4.467

[272 rows x 1 columns]

In [12]:
E_S = sum(eruptions[0])/272
E_S

3.4877830882352936

In [13]:
E_T = sum(waiting[0])/272
E_T

70.8970588235294

In [23]:
E_S2 = sum(np.square(eruptions[0]))/272
E_S2

13.46256976102941

In [29]:
E_T2 = sum(np.square(waiting[0]))/272
E_T2

5210.536764705882

In [35]:
Var_S = E_S2 - np.square(E_S)
Var_S

1.297938890449288

In [38]:
Var_T = E_T2 - np.square(E_T)
Var_T

184.14381487889295

In [44]:
E_ST = sum(eruptions[0]*waiting[0])/272
E_ST

261.1999816176469

In [47]:
Cov_ST = E_ST - E_S*E_T
Cov_ST

13.926418847318274

In [91]:
eruptions_sort = eruptions
eruptions_sort.sort_values(by=[0],na_position='first',inplace=True)
eruptions_sort = eruptions_sort.reset_index(drop=False)
eruptions_sort
print(eruptions_sort.iloc[[66]])
print(eruptions_sort.iloc[[67]])
print(eruptions_sort.iloc[[68]])


print(eruptions_sort.iloc[[133]])
print(eruptions_sort.iloc[[134]])
print(eruptions_sort.iloc[[135]])
print(eruptions_sort.iloc[[136]])
print(eruptions_sort.iloc[[137]])
print(eruptions_sort.iloc[[138]])
print(eruptions_sort.iloc[[139]])
print(eruptions_sort.iloc[[140]])
print(eruptions_sort.iloc[[141]])

print(eruptions_sort.iloc[[202]])
print(eruptions_sort.iloc[[203]])
print(eruptions_sort.iloc[[204]])

    index      0
66    248  2.133
    index     0
67    268  2.15
    index      0
68     15  2.167
     index      0
133    159  3.967
     index    0
134    224  4.0
     index    0
135    155  4.0
     index    0
136    178  4.0
     index    0
137     89  4.0
     index    0
138     73  4.0
     index    0
139    151  4.0
     index      0
140     33  4.033
     index      0
141     70  4.033
     index     0
202    251  4.45
     index     0
203    257  4.45
     index      0
204    271  4.467

In [99]:
waiting_sort = waiting
waiting_sort.sort_values(by=[0],na_position='first',inplace=True)
waiting_sort = waiting_sort.reset_index(drop=False)


print(waiting_sort.iloc[[65]])
print(waiting_sort.iloc[[66]])
print(waiting_sort.iloc[[67]])
print(waiting_sort.iloc[[68]])
print(waiting_sort.iloc[[69]])
print(waiting_sort.iloc[[70]])



print(waiting_sort.iloc[[133]])
print(waiting_sort.iloc[[134]])
print(waiting_sort.iloc[[135]])
print(waiting_sort.iloc[[136]])
print(waiting_sort.iloc[[137]])
print(waiting_sort.iloc[[138]])
print(waiting_sort.iloc[[139]])
print(waiting_sort.iloc[[139]])
print(waiting_sort.iloc[[141]])
print(waiting_sort.iloc[[142]])
print(waiting_sort.iloc[[143]])


print(waiting_sort.iloc[[200]])
print(waiting_sort.iloc[[201]])
print(waiting_sort.iloc[[202]])
print(waiting_sort.iloc[[203]])
print(waiting_sort.iloc[[204]])
print(waiting_sort.iloc[[205]])
print(waiting_sort.iloc[[206]])
print(waiting_sort.iloc[[207]])
print(waiting_sort.iloc[[208]])
print(waiting_sort.iloc[[209]])
print(waiting_sort.iloc[[210]])
print(waiting_sort.iloc[[211]])
print(waiting_sort.iloc[[212]])
print(waiting_sort.iloc[[213]])

    index   0
65    191  57
    index   0
66     43  58
    index   0
67    162  58
    index   0
68    262  58
    index   0
69     41  58
    index   0
70     49  59
     index   0
133    213  75
     index   0
134    219  76
     index   0
135    165  76
     index   0
136    215  76
     index   0
137     27  76
     index   0
138    144  76
     index   0
139    192  76
     index   0
139    192  76
     index   0
141     86  76
     index   0
142     75  76
     index   0
143    143  77
     index   0
200    195  81
     index   0
201    127  82
     index   0
202    142  82
     index   0
203    247  82
     index   0
204    201  82
     index   0
205    135  82
     index   0
206     63  82
     index   0
207    245  82
     index   0
208     70  82
     index   0
209     81  82
     index   0
210     99  82
     index   0
211    221  82
     index   0
212     48  82
     index   0
213    103  83

In [110]:
eruptions = pd.read_csv('C://Users//47129//Desktop//geyser_csv//eruptions.csv',header=None)
waiting = pd.read_csv('C://Users//47129//Desktop//geyser_csv//waiting.csv',header=None)
eruptions.columns=['S']
eruptions
eruptions['X_long'] = eruptions.S.apply(lambda s: 1 if s > 3.25 else 0)
eruptions

         S  X_long
0    3.600       1
1    1.800       0
2    3.333       1
3    2.283       0
4    4.533       1
5    2.883       0
6    4.700       1
7    3.600       1
8    1.950       0
9    4.350       1
10   1.833       0
11   3.917       1
12   4.200       1
13   1.750       0
14   4.700       1
15   2.167       0
16   1.750       0
17   4.800       1
18   1.600       0
19   4.250       1
20   1.800       0
21   1.750       0
22   3.450       1
23   3.067       0
24   4.533       1
25   3.600       1
26   1.967       0
27   4.083       1
28   3.850       1
29   4.433       1
..     ...     ...
242  4.933       1
243  2.900       0
244  4.583       1
245  3.833       1
246  2.083       0
247  4.367       1
248  2.133       0
249  4.350       1
250  2.200       0
251  4.450       1
252  3.567       1
253  4.500       1
254  4.150       1
255  3.817       1
256  3.917       1
257  4.450       1
258  2.000       0
259  4.283       1
260  4.767       1
261  4.533       1
262  1.850       0
263  4.250       1
264  1.983       0
265  2.250       0
266  4.750       1
267  4.117       1
268  2.150       0
269  4.417       1
270  1.817       0
271  4.467       1

[272 rows x 2 columns]

In [111]:
waiting.columns=['S']
waiting
waiting['Y_long'] = waiting.S.apply(lambda t: 1 if t > 68 else 0)
waiting

      S  Y_long
0    79       1
1    54       0
2    74       1
3    62       0
4    85       1
5    55       0
6    88       1
7    85       1
8    51       0
9    85       1
10   54       0
11   84       1
12   78       1
13   47       0
14   83       1
15   52       0
16   62       0
17   84       1
18   52       0
19   79       1
20   51       0
21   47       0
22   78       1
23   69       1
24   74       1
25   83       1
26   55       0
27   76       1
28   78       1
29   79       1
..   ..     ...
242  86       1
243  63       0
244  85       1
245  82       1
246  57       0
247  82       1
248  67       0
249  74       1
250  54       0
251  83       1
252  73       1
253  73       1
254  88       1
255  80       1
256  71       1
257  83       1
258  56       0
259  79       1
260  78       1
261  84       1
262  58       0
263  83       1
264  43       0
265  60       0
266  75       1
267  81       1
268  46       0
269  90       1
270  46       0
271  74       1

[272 rows x 2 columns]

In [112]:
com = pd.concat([eruptions, waiting], axis=1)
com

         S  X_long   S  Y_long
0    3.600       1  79       1
1    1.800       0  54       0
2    3.333       1  74       1
3    2.283       0  62       0
4    4.533       1  85       1
5    2.883       0  55       0
6    4.700       1  88       1
7    3.600       1  85       1
8    1.950       0  51       0
9    4.350       1  85       1
10   1.833       0  54       0
11   3.917       1  84       1
12   4.200       1  78       1
13   1.750       0  47       0
14   4.700       1  83       1
15   2.167       0  52       0
16   1.750       0  62       0
17   4.800       1  84       1
18   1.600       0  52       0
19   4.250       1  79       1
20   1.800       0  51       0
21   1.750       0  47       0
22   3.450       1  78       1
23   3.067       0  69       1
24   4.533       1  74       1
25   3.600       1  83       1
26   1.967       0  55       0
27   4.083       1  76       1
28   3.850       1  78       1
29   4.433       1  79       1
..     ...     ...  ..     ...
242  4.933       1  86       1
243  2.900       0  63       0
244  4.583       1  85       1
245  3.833       1  82       1
246  2.083       0  57       0
247  4.367       1  82       1
248  2.133       0  67       0
249  4.350       1  74       1
250  2.200       0  54       0
251  4.450       1  83       1
252  3.567       1  73       1
253  4.500       1  73       1
254  4.150       1  88       1
255  3.817       1  80       1
256  3.917       1  71       1
257  4.450       1  83       1
258  2.000       0  56       0
259  4.283       1  79       1
260  4.767       1  78       1
261  4.533       1  84       1
262  1.850       0  58       0
263  4.250       1  83       1
264  1.983       0  43       0
265  2.250       0  60       0
266  4.750       1  75       1
267  4.117       1  81       1
268  2.150       0  46       0
269  4.417       1  90       1
270  1.817       0  46       0
271  4.467       1  74       1

[272 rows x 4 columns]

In [115]:
def X1Y1(a, b):
    if a==1 and b==1:
        return 1
    else:
        return 0
com['X1Y1'] = com.apply(lambda x: X1Y1(x.X_long, x.Y_long), axis = 1)
com

         S  X_long   S  Y_long  X1Y1
0    3.600       1  79       1     1
1    1.800       0  54       0     0
2    3.333       1  74       1     1
3    2.283       0  62       0     0
4    4.533       1  85       1     1
5    2.883       0  55       0     0
6    4.700       1  88       1     1
7    3.600       1  85       1     1
8    1.950       0  51       0     0
9    4.350       1  85       1     1
10   1.833       0  54       0     0
11   3.917       1  84       1     1
12   4.200       1  78       1     1
13   1.750       0  47       0     0
14   4.700       1  83       1     1
15   2.167       0  52       0     0
16   1.750       0  62       0     0
17   4.800       1  84       1     1
18   1.600       0  52       0     0
19   4.250       1  79       1     1
20   1.800       0  51       0     0
21   1.750       0  47       0     0
22   3.450       1  78       1     1
23   3.067       0  69       1     0
24   4.533       1  74       1     1
25   3.600       1  83       1     1
26   1.967       0  55       0     0
27   4.083       1  76       1     1
28   3.850       1  78       1     1
29   4.433       1  79       1     1
..     ...     ...  ..     ...   ...
242  4.933       1  86       1     1
243  2.900       0  63       0     0
244  4.583       1  85       1     1
245  3.833       1  82       1     1
246  2.083       0  57       0     0
247  4.367       1  82       1     1
248  2.133       0  67       0     0
249  4.350       1  74       1     1
250  2.200       0  54       0     0
251  4.450       1  83       1     1
252  3.567       1  73       1     1
253  4.500       1  73       1     1
254  4.150       1  88       1     1
255  3.817       1  80       1     1
256  3.917       1  71       1     1
257  4.450       1  83       1     1
258  2.000       0  56       0     0
259  4.283       1  79       1     1
260  4.767       1  78       1     1
261  4.533       1  84       1     1
262  1.850       0  58       0     0
263  4.250       1  83       1     1
264  1.983       0  43       0     0
265  2.250       0  60       0     0
266  4.750       1  75       1     1
267  4.117       1  81       1     1
268  2.150       0  46       0     0
269  4.417       1  90       1     1
270  1.817       0  46       0     0
271  4.467       1  74       1     1

[272 rows x 5 columns]

In [116]:
def X1Y0(a, b):
    if a==1 and b==0:
        return 1
    else:
        return 0
com['X1Y0'] = com.apply(lambda x: X1Y0(x.X_long, x.Y_long), axis = 1)
com

         S  X_long   S  Y_long  X1Y1  X1Y0
0    3.600       1  79       1     1     0
1    1.800       0  54       0     0     0
2    3.333       1  74       1     1     0
3    2.283       0  62       0     0     0
4    4.533       1  85       1     1     0
5    2.883       0  55       0     0     0
6    4.700       1  88       1     1     0
7    3.600       1  85       1     1     0
8    1.950       0  51       0     0     0
9    4.350       1  85       1     1     0
10   1.833       0  54       0     0     0
11   3.917       1  84       1     1     0
12   4.200       1  78       1     1     0
13   1.750       0  47       0     0     0
14   4.700       1  83       1     1     0
15   2.167       0  52       0     0     0
16   1.750       0  62       0     0     0
17   4.800       1  84       1     1     0
18   1.600       0  52       0     0     0
19   4.250       1  79       1     1     0
20   1.800       0  51       0     0     0
21   1.750       0  47       0     0     0
22   3.450       1  78       1     1     0
23   3.067       0  69       1     0     0
24   4.533       1  74       1     1     0
25   3.600       1  83       1     1     0
26   1.967       0  55       0     0     0
27   4.083       1  76       1     1     0
28   3.850       1  78       1     1     0
29   4.433       1  79       1     1     0
..     ...     ...  ..     ...   ...   ...
242  4.933       1  86       1     1     0
243  2.900       0  63       0     0     0
244  4.583       1  85       1     1     0
245  3.833       1  82       1     1     0
246  2.083       0  57       0     0     0
247  4.367       1  82       1     1     0
248  2.133       0  67       0     0     0
249  4.350       1  74       1     1     0
250  2.200       0  54       0     0     0
251  4.450       1  83       1     1     0
252  3.567       1  73       1     1     0
253  4.500       1  73       1     1     0
254  4.150       1  88       1     1     0
255  3.817       1  80       1     1     0
256  3.917       1  71       1     1     0
257  4.450       1  83       1     1     0
258  2.000       0  56       0     0     0
259  4.283       1  79       1     1     0
260  4.767       1  78       1     1     0
261  4.533       1  84       1     1     0
262  1.850       0  58       0     0     0
263  4.250       1  83       1     1     0
264  1.983       0  43       0     0     0
265  2.250       0  60       0     0     0
266  4.750       1  75       1     1     0
267  4.117       1  81       1     1     0
268  2.150       0  46       0     0     0
269  4.417       1  90       1     1     0
270  1.817       0  46       0     0     0
271  4.467       1  74       1     1     0

[272 rows x 6 columns]

In [117]:
def X0Y0(a, b):
    if a==0 and b==0:
        return 1
    else:
        return 0
com['X0Y0'] = com.apply(lambda x: X0Y0(x.X_long, x.Y_long), axis = 1)
com

         S  X_long   S  Y_long  X1Y1  X1Y0  X0Y0
0    3.600       1  79       1     1     0     0
1    1.800       0  54       0     0     0     1
2    3.333       1  74       1     1     0     0
3    2.283       0  62       0     0     0     1
4    4.533       1  85       1     1     0     0
5    2.883       0  55       0     0     0     1
6    4.700       1  88       1     1     0     0
7    3.600       1  85       1     1     0     0
8    1.950       0  51       0     0     0     1
9    4.350       1  85       1     1     0     0
10   1.833       0  54       0     0     0     1
11   3.917       1  84       1     1     0     0
12   4.200       1  78       1     1     0     0
13   1.750       0  47       0     0     0     1
14   4.700       1  83       1     1     0     0
15   2.167       0  52       0     0     0     1
16   1.750       0  62       0     0     0     1
17   4.800       1  84       1     1     0     0
18   1.600       0  52       0     0     0     1
19   4.250       1  79       1     1     0     0
20   1.800       0  51       0     0     0     1
21   1.750       0  47       0     0     0     1
22   3.450       1  78       1     1     0     0
23   3.067       0  69       1     0     0     0
24   4.533       1  74       1     1     0     0
25   3.600       1  83       1     1     0     0
26   1.967       0  55       0     0     0     1
27   4.083       1  76       1     1     0     0
28   3.850       1  78       1     1     0     0
29   4.433       1  79       1     1     0     0
..     ...     ...  ..     ...   ...   ...   ...
242  4.933       1  86       1     1     0     0
243  2.900       0  63       0     0     0     1
244  4.583       1  85       1     1     0     0
245  3.833       1  82       1     1     0     0
246  2.083       0  57       0     0     0     1
247  4.367       1  82       1     1     0     0
248  2.133       0  67       0     0     0     1
249  4.350       1  74       1     1     0     0
250  2.200       0  54       0     0     0     1
251  4.450       1  83       1     1     0     0
252  3.567       1  73       1     1     0     0
253  4.500       1  73       1     1     0     0
254  4.150       1  88       1     1     0     0
255  3.817       1  80       1     1     0     0
256  3.917       1  71       1     1     0     0
257  4.450       1  83       1     1     0     0
258  2.000       0  56       0     0     0     1
259  4.283       1  79       1     1     0     0
260  4.767       1  78       1     1     0     0
261  4.533       1  84       1     1     0     0
262  1.850       0  58       0     0     0     1
263  4.250       1  83       1     1     0     0
264  1.983       0  43       0     0     0     1
265  2.250       0  60       0     0     0     1
266  4.750       1  75       1     1     0     0
267  4.117       1  81       1     1     0     0
268  2.150       0  46       0     0     0     1
269  4.417       1  90       1     1     0     0
270  1.817       0  46       0     0     0     1
271  4.467       1  74       1     1     0     0

[272 rows x 7 columns]

In [118]:
def X0Y1(a, b):
    if a==0 and b==1:
        return 1
    else:
        return 0
com['X0Y1'] = com.apply(lambda x: X0Y1(x.X_long, x.Y_long), axis = 1)
com

         S  X_long   S  Y_long  X1Y1  X1Y0  X0Y0  X0Y1
0    3.600       1  79       1     1     0     0     0
1    1.800       0  54       0     0     0     1     0
2    3.333       1  74       1     1     0     0     0
3    2.283       0  62       0     0     0     1     0
4    4.533       1  85       1     1     0     0     0
5    2.883       0  55       0     0     0     1     0
6    4.700       1  88       1     1     0     0     0
7    3.600       1  85       1     1     0     0     0
8    1.950       0  51       0     0     0     1     0
9    4.350       1  85       1     1     0     0     0
10   1.833       0  54       0     0     0     1     0
11   3.917       1  84       1     1     0     0     0
12   4.200       1  78       1     1     0     0     0
13   1.750       0  47       0     0     0     1     0
14   4.700       1  83       1     1     0     0     0
15   2.167       0  52       0     0     0     1     0
16   1.750       0  62       0     0     0     1     0
17   4.800       1  84       1     1     0     0     0
18   1.600       0  52       0     0     0     1     0
19   4.250       1  79       1     1     0     0     0
20   1.800       0  51       0     0     0     1     0
21   1.750       0  47       0     0     0     1     0
22   3.450       1  78       1     1     0     0     0
23   3.067       0  69       1     0     0     0     1
24   4.533       1  74       1     1     0     0     0
25   3.600       1  83       1     1     0     0     0
26   1.967       0  55       0     0     0     1     0
27   4.083       1  76       1     1     0     0     0
28   3.850       1  78       1     1     0     0     0
29   4.433       1  79       1     1     0     0     0
..     ...     ...  ..     ...   ...   ...   ...   ...
242  4.933       1  86       1     1     0     0     0
243  2.900       0  63       0     0     0     1     0
244  4.583       1  85       1     1     0     0     0
245  3.833       1  82       1     1     0     0     0
246  2.083       0  57       0     0     0     1     0
247  4.367       1  82       1     1     0     0     0
248  2.133       0  67       0     0     0     1     0
249  4.350       1  74       1     1     0     0     0
250  2.200       0  54       0     0     0     1     0
251  4.450       1  83       1     1     0     0     0
252  3.567       1  73       1     1     0     0     0
253  4.500       1  73       1     1     0     0     0
254  4.150       1  88       1     1     0     0     0
255  3.817       1  80       1     1     0     0     0
256  3.917       1  71       1     1     0     0     0
257  4.450       1  83       1     1     0     0     0
258  2.000       0  56       0     0     0     1     0
259  4.283       1  79       1     1     0     0     0
260  4.767       1  78       1     1     0     0     0
261  4.533       1  84       1     1     0     0     0
262  1.850       0  58       0     0     0     1     0
263  4.250       1  83       1     1     0     0     0
264  1.983       0  43       0     0     0     1     0
265  2.250       0  60       0     0     0     1     0
266  4.750       1  75       1     1     0     0     0
267  4.117       1  81       1     1     0     0     0
268  2.150       0  46       0     0     0     1     0
269  4.417       1  90       1     1     0     0     0
270  1.817       0  46       0     0     0     1     0
271  4.467       1  74       1     1     0     0     0

[272 rows x 8 columns]

In [119]:
X1Y1=com['X1Y1'].sum()
X1Y0=com['X1Y0'].sum()
X0Y0=com['X0Y0'].sum()
X0Y1=com['X0Y1'].sum()

In [122]:
print(X1Y1)
print(X1Y0)
print(X0Y0)
print(X0Y1)

169
5
96
2